ALTER TABLE VINMONOPOLET_BATCH_TOP_LIST_RECORDS ADD changeInRanking VARCHAR(5);

ALTER TABLE VINMONOPOLET_BATCH_TOP_LIST_RECORDS
    DROP FOREIGN KEY VINMONOPOLET_BATCH_TOP_LIST_RECORDS_ibfk_1;

ALTER TABLE VINMONOPOLET_BATCH_TOP_LIST_RECORDS
    ADD CONSTRAINT FK_BATCH_TABLE
        FOREIGN KEY (fk_vinmonopoletBatchID)
            REFERENCES VINMONOPOLET_BATCH(batchId)
            ON DELETE CASCADE ON UPDATE NO ACTION;